try {
  console.log(a + b);
  //   throw new ReferenceError();
} catch (error) {
  console.log(error);
  console.log("There was error");
  console.log("The error was saved in the error log");
}
console.log("My Program Does't Stop", "I am still here", "777");
// Work 24/1/24
//Great Work!
